{"name": "test_login_with_valid_email_and_invalid_password", "status": "passed", "start": 1747716699138, "stop": 1747716701052, "uuid": "719b3a18-779c-4b2a-b2d6-c30ae5866ce8", "historyId": "07eb39407adceff4cfeffeb6c905a5b6", "testCaseId": "07eb39407adceff4cfeffeb6c905a5b6", "fullName": "test.test_login.TestLogin#test_login_with_valid_email_and_invalid_password", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup', 'log_on_failure')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "TeamOs-PC"}, {"name": "thread", "value": "10640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login"}]}